export const FIELD_FULL_NAMES: Record<string, string> = {
    age: "Age",
    bp: "Blood Pressure",
    sg: "Specific Gravity",
    al: "Albumin",
    su: "Sugar",
    rbc: "Red Blood Cells",
    pc: "Pus Cell",
    pcc: "Pus Cell Clumps",
    ba: "Bacteria",
    bgr: "Blood Glucose Random",
    bu: "Blood Urea",
    sc: "Serum Creatinine",
    sod: "Sodium",
    pot: "Potassium",
    hemo: "Hemoglobin",
    pcv: "Packed Cell Volume",
    wc: "White Blood Cell Count",
    rc: "Red Blood Cell Count",
    htn: "Hypertension",
    dm: "Diabetes Mellitus",
    cad: "Coronary Artery Disease",
    appet: "Appetite",
    pe: "Pedal Edema",
    ane: "Anemia",
};